[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # Variables VITE para el frontend (build time)
  VITE_SUPABASE_URL = "https://fcvwqwjsypossdqochde.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjdndxd2pzeXBvc3NkcW9jaGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDAwODcsImV4cCI6MjA3MTgxNjA4N30.FK40wJgJyHDnte-JLVdlvDLRsIIs3lReKkZLSpNYSgk"
  VITE_APP_LOGO_URL = "https://abundiss.com/wp-content/uploads/2021/11/LogoB.png"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Función programada para refresh automático de tokens cada 12 horas
[[scheduled.functions]]
  schedule = "0 */12 * * *"
  path = "/.netlify/functions/kommo-scheduled-refresh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
